//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foxconn.App.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Black {
            get {
                return ((global::System.Drawing.Color)(this["Black"]));
            }
            set {
                this["Black"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 59, 48")]
        public global::System.Drawing.Color Red {
            get {
                return ((global::System.Drawing.Color)(this["Red"]));
            }
            set {
                this["Red"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 149, 0")]
        public global::System.Drawing.Color Orange {
            get {
                return ((global::System.Drawing.Color)(this["Orange"]));
            }
            set {
                this["Orange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 204, 0")]
        public global::System.Drawing.Color Yellow {
            get {
                return ((global::System.Drawing.Color)(this["Yellow"]));
            }
            set {
                this["Yellow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 205, 65")]
        public global::System.Drawing.Color Green {
            get {
                return ((global::System.Drawing.Color)(this["Green"]));
            }
            set {
                this["Green"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 199, 190")]
        public global::System.Drawing.Color Mint {
            get {
                return ((global::System.Drawing.Color)(this["Mint"]));
            }
            set {
                this["Mint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("89, 173, 196")]
        public global::System.Drawing.Color Teal {
            get {
                return ((global::System.Drawing.Color)(this["Teal"]));
            }
            set {
                this["Teal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("85, 190, 240")]
        public global::System.Drawing.Color Cyan {
            get {
                return ((global::System.Drawing.Color)(this["Cyan"]));
            }
            set {
                this["Cyan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 122, 255")]
        public global::System.Drawing.Color Blue {
            get {
                return ((global::System.Drawing.Color)(this["Blue"]));
            }
            set {
                this["Blue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("88, 86, 214")]
        public global::System.Drawing.Color Indigo {
            get {
                return ((global::System.Drawing.Color)(this["Indigo"]));
            }
            set {
                this["Indigo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("175, 82, 222")]
        public global::System.Drawing.Color Purple {
            get {
                return ((global::System.Drawing.Color)(this["Purple"]));
            }
            set {
                this["Purple"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 45, 85")]
        public global::System.Drawing.Color Pink {
            get {
                return ((global::System.Drawing.Color)(this["Pink"]));
            }
            set {
                this["Pink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("162, 132, 94")]
        public global::System.Drawing.Color Brown {
            get {
                return ((global::System.Drawing.Color)(this["Brown"]));
            }
            set {
                this["Brown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("142, 142, 147")]
        public global::System.Drawing.Color Gray {
            get {
                return ((global::System.Drawing.Color)(this["Gray"]));
            }
            set {
                this["Gray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("174, 174, 178")]
        public global::System.Drawing.Color Gray2 {
            get {
                return ((global::System.Drawing.Color)(this["Gray2"]));
            }
            set {
                this["Gray2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("199, 199, 204")]
        public global::System.Drawing.Color Gray3 {
            get {
                return ((global::System.Drawing.Color)(this["Gray3"]));
            }
            set {
                this["Gray3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("209, 209, 214")]
        public global::System.Drawing.Color Gray4 {
            get {
                return ((global::System.Drawing.Color)(this["Gray4"]));
            }
            set {
                this["Gray4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("229, 229, 234")]
        public global::System.Drawing.Color Gray5 {
            get {
                return ((global::System.Drawing.Color)(this["Gray5"]));
            }
            set {
                this["Gray5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("242, 242, 247")]
        public global::System.Drawing.Color Gray6 {
            get {
                return ((global::System.Drawing.Color)(this["Gray6"]));
            }
            set {
                this["Gray6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color White {
            get {
                return ((global::System.Drawing.Color)(this["White"]));
            }
            set {
                this["White"] = value;
            }
        }
    }
}
